apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-basics-test
  namespace: app-basics-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-basics-test
  template:
    metadata:
      labels:
        app: app-basics-test
    spec:
      containers:
      - name: app-basics-test
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
        - containerPort: 8080
      healthCheck:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
---
