namespace: dev

deployment:
  replicas: 2
  container:
    image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0


service:
  name: app-basics-test

ingress:
  host: dev.icarus-lab.org
  path: /dev
  certificate: certificate-letsencrypt-dev

issuer:
  name: letsencrypt-dev
  server: https://acme-v02.api.letsencrypt.org/directory
  email: rdgc91@gmail.com
  privateKeySecretRef:
    name: secret-letsencrypt-dev
  ingress:
    class: ingress-nginx
  secretName: letsencrypt-dev
