namespace: pro

deployment:
  replicas: 2
  container:
    image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0

service:
  name: app-basics-test

ingress:
  host: pro.icarus-lab.org
  certificate: letsencrypt-pro

issuer:
  name: letsencrypt-pro
  server: https://acme-v02.api.letsencrypt.org/directory
  email: rdgc91@gmail.com
  privateKeySecretRef:
    name: letsencrypt-pro
  ingress:
    class: ingress-nginx
  secretName: letsencrypt-pro
