namespace: staging

deployment:
  replicas: 2
  container:
    image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0

service:
  name: app-basics-test

ingress:
  host: staging.icarus-lab.org
  certificate: certificate-letsencrypt-staging

issuer:
  name: letsencrypt-staging
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  email: rdgc91@gmail.com
  privateKeySecretRef:
    name: secret-letsencrypt-staging
  ingress:
    class: ingress-nginx
  secretName: letsencrypt-staging
