namespace: staging

deployment:
  replicas: 2
  container:
    image: us-docker.pkg.staging/google-samples/containers/gke/hello-app:2.0

service:
  name: staging-app-basics-test

ingress:
  host: staging.app.lab.com
