apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: nginx-controller
    meta.helm.sh/release-namespace: nginx-controller
  labels:
    app.kubernetes.io/instance: nginx-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/version: 3.4.2
    helm.sh/chart: nginx-ingress-1.1.2
  name: nginx-controller-nginx-ingress-controller
  namespace: nginx-controller
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  healthCheckNodePort: 30784
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30948
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30949
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/instance: nginx-controller
    app.kubernetes.io/name: nginx-ingress
  sessionAffinity: None
  type: LoadBalancer
