kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: study
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30950
    hostPort: 8080
  - containerPort: 30948
    hostPort: 8081
  - containerPort: 30949
    hostPort: 8082

