apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-basics-test-pro
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rGarmendia/argocd
    targetRevision: HEAD
    path: helm-chart/chart/app-basics-test
    helm:
      valueFiles:
        - pro-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pro
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
